8.Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [1]:
import numpy as np

In [2]:
a = np.array(5)

In [4]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [6]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [10]:
a = np.array([[10,20,30], [40,50,60]])
a

array([[10, 20, 30],
       [40, 50, 60]])

In [11]:
a = np.arange(10,70,10).reshape(2,3)
a

array([[10, 20, 30],
       [40, 50, 60]])

9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [12]:
import random

In [17]:
arr = np.random.randint(0,100,size=(4,4))
print(arr)

[[63 73 60 82]
 [ 1 46 92 23]
 [47 91 32 86]
 [71 21 11 82]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [18]:
import pandas as pd

b = np.array([[2,3,5],[6,7,8],[4,9,1]])
b

array([[2, 3, 5],
       [6, 7, 8],
       [4, 9, 1]])

In [19]:
df = pd.DataFrame(b,columns=['A','B','C'])
df

A  B  C
0  2  3  5
1  6  7  8
2  4  9  1

# Section C: 
 Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [48]:
import pandas as pd

data = {
    'Name': ['Sukhada','Shweta','Atharva','Parth','Piyush','Sarvesh','Ananya','Smita','Akshya','Zoha'],
    'Age': [22,25,22,20,27,24,22,32,29,21],
    'City': ['Dehli','Bangalore','Mumbai','Pune','Nashik','Nagpur','Pune','Mumbai','Bangalore','Dehli'],
    'Salary': [65000, 66000, 67000, 43000, 60000, 47000, 55000, 44000, 69000, 58000]
}

df = pd.DataFrame(data)
print(df)

      Name  Age       City  Salary
0  Sukhada   22      Dehli   65000
1   Shweta   25  Bangalore   66000
2  Atharva   22     Mumbai   67000
3    Parth   20       Pune   43000
4   Piyush   27     Nashik   60000
5  Sarvesh   24     Nagpur   47000
6   Ananya   22       Pune   55000
7    Smita   32     Mumbai   44000
8   Akshya   29  Bangalore   69000
9     Zoha   21      Dehli   58000


In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [50]:
df.describe()

Age       Salary
count  10.000000     10.00000
mean   24.400000  57400.00000
std     3.864367   9811.55781
min    20.000000  43000.00000
25%    22.000000  49000.00000
50%    23.000000  59000.00000
75%    26.500000  65750.00000
max    32.000000  69000.00000

In [51]:
Selecte_column = df[['Name','City']]
print(Selecte_column)

      Name       City
0  Sukhada      Dehli
1   Shweta  Bangalore
2  Atharva     Mumbai
3    Parth       Pune
4   Piyush     Nashik
5  Sarvesh     Nagpur
6   Ananya       Pune
7    Smita     Mumbai
8   Akshya  Bangalore
9     Zoha      Dehli


In [52]:
drop_data=df.drop('City',axis=1)
drop_data

Name  Age  Salary
0  Sukhada   22   65000
1   Shweta   25   66000
2  Atharva   22   67000
3    Parth   20   43000
4   Piyush   27   60000
5  Sarvesh   24   47000
6   Ananya   22   55000
7    Smita   32   44000
8   Akshya   29   69000
9     Zoha   21   58000

In [59]:
# Sample DataFrame with a missing value

data = {
    'Name': ['Sukhada','Shweta','Atharva','Parth','Piyush','Sarvesh','Ananya','Smita','Akshya','Zoha'],
    'Age': [22,25,22,20,27,24,22,32,29,21],
    'City': ['Dehli','Bangalore','Mumbai','Pune','Nashik','Nagpur','Pune','Mumbai','Bangalore','Dehli'],
    'Salary': [65000, 66000, 67000, None, 60000, 47000, 55000, 44000, 69000, 58000]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# Fill missing values in 'Salary' with the mean
mean_salary = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(mean_salary)
print("\nDataFrame after filling missing Salary with mean:")

print(df)

Original DataFrame:
      Name  Age       City   Salary
0  Sukhada   22      Dehli  65000.0
1   Shweta   25  Bangalore  66000.0
2  Atharva   22     Mumbai  67000.0
3    Parth   20       Pune      NaN
4   Piyush   27     Nashik  60000.0
5  Sarvesh   24     Nagpur  47000.0
6   Ananya   22       Pune  55000.0
7    Smita   32     Mumbai  44000.0
8   Akshya   29  Bangalore  69000.0
9     Zoha   21      Dehli  58000.0

DataFrame after filling missing Salary with mean:
      Name  Age       City   Salary
0  Sukhada   22      Dehli  65000.0
1   Shweta   25  Bangalore  66000.0
2  Atharva   22     Mumbai  67000.0
3    Parth   20       Pune  59000.0
4   Piyush   27     Nashik  60000.0
5  Sarvesh   24     Nagpur  47000.0
6   Ananya   22       Pune  55000.0
7    Smita   32     Mumbai  44000.0
8   Akshya   29  Bangalore  69000.0
9     Zoha   21      Dehli  58000.0
